// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: graph.proto
#ifndef GRPC_graph_2eproto__INCLUDED
#define GRPC_graph_2eproto__INCLUDED

#include "graph.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace proto {

class Graph_Service final {
 public:
  static constexpr char const* service_full_name() {
    return "proto.Graph_Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::proto::Graph_RouteResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_RouteResponse>> AsyncGetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_RouteResponse>>(AsyncGetRouteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_RouteResponse>> PrepareAsyncGetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_RouteResponse>>(PrepareAsyncGetRouteRaw(context, request, cq));
    }
    virtual ::grpc::Status SetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::proto::Graph_EmptyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_EmptyResponse>> AsyncSetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_EmptyResponse>>(AsyncSetConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_EmptyResponse>> PrepareAsyncSetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_EmptyResponse>>(PrepareAsyncSetConfigRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void SetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest* request, ::proto::Graph_EmptyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest* request, ::proto::Graph_EmptyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_RouteResponse>* AsyncGetRouteRaw(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_RouteResponse>* PrepareAsyncGetRouteRaw(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_EmptyResponse>* AsyncSetConfigRaw(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::proto::Graph_EmptyResponse>* PrepareAsyncSetConfigRaw(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::proto::Graph_RouteResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::Graph_RouteResponse>> AsyncGetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::Graph_RouteResponse>>(AsyncGetRouteRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::Graph_RouteResponse>> PrepareAsyncGetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::Graph_RouteResponse>>(PrepareAsyncGetRouteRaw(context, request, cq));
    }
    ::grpc::Status SetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::proto::Graph_EmptyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::Graph_EmptyResponse>> AsyncSetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::Graph_EmptyResponse>>(AsyncSetConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::Graph_EmptyResponse>> PrepareAsyncSetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::proto::Graph_EmptyResponse>>(PrepareAsyncSetConfigRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response, std::function<void(::grpc::Status)>) override;
      void GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void SetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest* request, ::proto::Graph_EmptyResponse* response, std::function<void(::grpc::Status)>) override;
      void SetConfig(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest* request, ::proto::Graph_EmptyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::proto::Graph_RouteResponse>* AsyncGetRouteRaw(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::proto::Graph_RouteResponse>* PrepareAsyncGetRouteRaw(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::proto::Graph_EmptyResponse>* AsyncSetConfigRaw(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::proto::Graph_EmptyResponse>* PrepareAsyncSetConfigRaw(::grpc::ClientContext* context, const ::proto::Graph_ConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetRoute_;
    const ::grpc::internal::RpcMethod rpcmethod_SetConfig_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetRoute(::grpc::ServerContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response);
    virtual ::grpc::Status SetConfig(::grpc::ServerContext* context, const ::proto::Graph_ConfigRequest* request, ::proto::Graph_EmptyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetRoute() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRoute(::grpc::ServerContext* /*context*/, const ::proto::Graph_RouteRequest* /*request*/, ::proto::Graph_RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRoute(::grpc::ServerContext* context, ::proto::Graph_RouteRequest* request, ::grpc::ServerAsyncResponseWriter< ::proto::Graph_RouteResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_SetConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetConfig() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_SetConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetConfig(::grpc::ServerContext* /*context*/, const ::proto::Graph_ConfigRequest* /*request*/, ::proto::Graph_EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetConfig(::grpc::ServerContext* context, ::proto::Graph_ConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::proto::Graph_EmptyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetRoute<WithAsyncMethod_SetConfig<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetRoute() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::proto::Graph_RouteRequest, ::proto::Graph_RouteResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response) { return this->GetRoute(context, request, response); }));}
    void SetMessageAllocatorFor_GetRoute(
        ::grpc::MessageAllocator< ::proto::Graph_RouteRequest, ::proto::Graph_RouteResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::proto::Graph_RouteRequest, ::proto::Graph_RouteResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRoute(::grpc::ServerContext* /*context*/, const ::proto::Graph_RouteRequest* /*request*/, ::proto::Graph_RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRoute(
      ::grpc::CallbackServerContext* /*context*/, const ::proto::Graph_RouteRequest* /*request*/, ::proto::Graph_RouteResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_SetConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetConfig() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::proto::Graph_ConfigRequest, ::proto::Graph_EmptyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::proto::Graph_ConfigRequest* request, ::proto::Graph_EmptyResponse* response) { return this->SetConfig(context, request, response); }));}
    void SetMessageAllocatorFor_SetConfig(
        ::grpc::MessageAllocator< ::proto::Graph_ConfigRequest, ::proto::Graph_EmptyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::proto::Graph_ConfigRequest, ::proto::Graph_EmptyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetConfig(::grpc::ServerContext* /*context*/, const ::proto::Graph_ConfigRequest* /*request*/, ::proto::Graph_EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::proto::Graph_ConfigRequest* /*request*/, ::proto::Graph_EmptyResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetRoute<WithCallbackMethod_SetConfig<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetRoute() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRoute(::grpc::ServerContext* /*context*/, const ::proto::Graph_RouteRequest* /*request*/, ::proto::Graph_RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_SetConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetConfig() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_SetConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetConfig(::grpc::ServerContext* /*context*/, const ::proto::Graph_ConfigRequest* /*request*/, ::proto::Graph_EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetRoute() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRoute(::grpc::ServerContext* /*context*/, const ::proto::Graph_RouteRequest* /*request*/, ::proto::Graph_RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetRoute(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetConfig() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_SetConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetConfig(::grpc::ServerContext* /*context*/, const ::proto::Graph_ConfigRequest* /*request*/, ::proto::Graph_EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetConfig(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetRoute() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetRoute(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetRoute(::grpc::ServerContext* /*context*/, const ::proto::Graph_RouteRequest* /*request*/, ::proto::Graph_RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetRoute(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetConfig() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetConfig(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetConfig(::grpc::ServerContext* /*context*/, const ::proto::Graph_ConfigRequest* /*request*/, ::proto::Graph_EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetRoute : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetRoute() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::proto::Graph_RouteRequest, ::proto::Graph_RouteResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::proto::Graph_RouteRequest, ::proto::Graph_RouteResponse>* streamer) {
                       return this->StreamedGetRoute(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetRoute() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetRoute(::grpc::ServerContext* /*context*/, const ::proto::Graph_RouteRequest* /*request*/, ::proto::Graph_RouteResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetRoute(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::proto::Graph_RouteRequest,::proto::Graph_RouteResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetConfig() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::proto::Graph_ConfigRequest, ::proto::Graph_EmptyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::proto::Graph_ConfigRequest, ::proto::Graph_EmptyResponse>* streamer) {
                       return this->StreamedSetConfig(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetConfig(::grpc::ServerContext* /*context*/, const ::proto::Graph_ConfigRequest* /*request*/, ::proto::Graph_EmptyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetConfig(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::proto::Graph_ConfigRequest,::proto::Graph_EmptyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetRoute<WithStreamedUnaryMethod_SetConfig<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetRoute<WithStreamedUnaryMethod_SetConfig<Service > > StreamedService;
};

}  // namespace proto


#endif  // GRPC_graph_2eproto__INCLUDED
