// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: graph.proto

#include "graph.pb.h"
#include "graph.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace proto {

static const char* Graph__method_names[] = {
  "/proto.Graph_/GetRoute",
};

std::unique_ptr< Graph_::Stub> Graph_::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Graph_::Stub> stub(new Graph_::Stub(channel, options));
  return stub;
}

Graph_::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetRoute_(Graph__method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Graph_::Stub::GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::proto::Graph_RouteResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::proto::Graph_RouteRequest, ::proto::Graph_RouteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetRoute_, context, request, response);
}

void Graph_::Stub::async::GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::proto::Graph_RouteRequest, ::proto::Graph_RouteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRoute_, context, request, response, std::move(f));
}

void Graph_::Stub::async::GetRoute(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetRoute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::proto::Graph_RouteResponse>* Graph_::Stub::PrepareAsyncGetRouteRaw(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::proto::Graph_RouteResponse, ::proto::Graph_RouteRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetRoute_, context, request);
}

::grpc::ClientAsyncResponseReader< ::proto::Graph_RouteResponse>* Graph_::Stub::AsyncGetRouteRaw(::grpc::ClientContext* context, const ::proto::Graph_RouteRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetRouteRaw(context, request, cq);
  result->StartCall();
  return result;
}

Graph_::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Graph__method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Graph_::Service, ::proto::Graph_RouteRequest, ::proto::Graph_RouteResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Graph_::Service* service,
             ::grpc::ServerContext* ctx,
             const ::proto::Graph_RouteRequest* req,
             ::proto::Graph_RouteResponse* resp) {
               return service->GetRoute(ctx, req, resp);
             }, this)));
}

Graph_::Service::~Service() {
}

::grpc::Status Graph_::Service::GetRoute(::grpc::ServerContext* context, const ::proto::Graph_RouteRequest* request, ::proto::Graph_RouteResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace proto

