# temporary suppress, remove in future
if (NOT DEFINED CMAKE_SUPPRESS_DEVELOPER_WARNINGS)
    set(CMAKE_SUPPRESS_DEVELOPER_WARNINGS 1 CACHE INTERNAL "No dev warnings")
endif()

find_package(cppzmq CONFIG REQUIRED)
if (TARGET cppzmq)
    add_library(LibZmq ALIAS cppzmq)
endif()

find_package(gRPC CONFIG REQUIRED)
if (TARGET gRPC::gpr)
    add_library(LibGrpcGpr ALIAS gRPC::gpr)
endif()
if (TARGET gRPC::upb)
    add_library(LibGrpcUpb ALIAS gRPC::upb)
endif()
if (TARGET gRPC::grpc)
    add_library(LibGrpcGrpc ALIAS gRPC::grpc)
endif()
if (TARGET gRPC::grpc++)
    add_library(LibGrpcGrpcpp ALIAS gRPC::grpc++)
endif()
if (TARGET gRPC::grpc++_reflection)
    add_library(LibGrpcReflection ALIAS gRPC::grpc++_reflection)
endif()

find_package(nlohmann_json CONFIG REQUIRED)
if (TARGET nlohmann_json::nlohmann_json)
    add_library(LibNlohmannJson ALIAS nlohmann_json::nlohmann_json)
endif()
